name: 'Colony Validate'
description: 'Validates colony blueprints against specific repo'
author: 'Quali'
inputs:
  space:
    description: 'Colony space'
    required: true

  filelist:
    description: 'Whitespace separated list of files to validate'
    required: true 

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.space }}
    - ${{ inputs.filelist }}
