name: 'Colony Validate'
description: 'Validates colony blueprints against specific repo'
author: 'Quali'
inputs:
  space:
    description: 'Colony space'
    required: true
  token:
    description: >
      colony_token
    required: true
  github_token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
  debug:
    description: 'Enable debug logging'
    required: false
    default: 'false'

runs:
  using: 'node12'
  main: 'index.js'
