name: 'Start Colony Sandbox'
description: 'Starts a sandbox in Colony and returns its ID'
author: 'Quali'
inputs:
  space:
    description: 'Colony space'
    required: false
  blueprint_name:
    description: 'Name of Blueprint'
    required: false
  sandbox_name:
    description: 'Colony Sandbox Name'
    required: false
  colony_token:
    description: 'Colony longterm token'
    required: true

outputs:
  sandbox_id:
    description: 'The ID of launched Colony Sandbox'
    value: ${{ steps.start-sandbox.outputs.sandbox-id }}

runs:
  using: "composite"
  steps:
    - id: start-sandbox
      # run: .github/actions/start-sandbox/start-sb.sh
      # run: ${{ github.action_path }}/start-sb.sh
      run: |
        echo "Current DIR"
        ls -la
        echo "Sandbox with id $sb has been started"

      shell: bash
