name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        space: [ PreSaleJenkinsSolution, promotions-manager ]

    steps:
    - uses: actions/checkout@v1
    - name: Get changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: Colony validate blueprints
      uses: ddovbii/colony-validate-bps@0.0.1
      with:
        space: ${{ matrix.space }}
        fileslist: ${{ steps.files.outputs.all }}
        colony_token: ${{ secrets.COLONY_TOKEN }}
