name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Colony start sandbox
      uses: ./.github/actions/start-sandbox
      with:
        space: team2
        blueprint_name: hello-private-ip-aws
        sandbox_name: test-sb
        colony_token: ${{ secrets.COLONY_TOKEN }}
