name: CI

push:
  branches:
    - switch-to-own-image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: Colony validate blueprints
      uses: ./.github/actions/validate-bps
      with:
<<<<<<< HEAD:.github/workflows/ci.yml
        space: ${{ matrix.space }}
<<<<<<< HEAD
<<<<<<< HEAD
=======
        space: promotions-manager
>>>>>>> two ci:.github/workflows/develop_ci.yml
        fileslist: ${{ steps.files.outputs.all }}
        colony_token: ${{ secrets.COLONY_TOKEN }}
=======
        filelist: ${{ steps.files.outputs.all }}
>>>>>>> pass changed files
=======
        fileslist: ${{ steps.files.outputs.all }}
        colony_token: ${{ secrets.COLONY_TOKEN }}
>>>>>>> move token to inputs
