name: CI
on:
  push:
    branches:
      - switch-to-own-image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: Colony validate blueprints
      uses: ./.github/actions/validate-bps
      with:
        space: promotions-manager
        files_list: ${{ steps.files.outputs.all }}
        colony_token: ${{ secrets.COLONY_TOKEN }}
