name: CI

push:
  branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: Colony validate blueprints
      uses: ddovbii/colony-validate-bps@0.0.3
      with:
        space: promotions-manager
        fileslist: ${{ steps.files.outputs.all }}
        colony_token: ${{ secrets.COLONY_TOKEN }}
