name: CI
on:
  push:
    branches:
      - master
    pull_request:
      branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get changed files
      id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - name: Colony validate blueprints
      uses: QualiSystemsLab/colony-validate-bp-action@v0.0.1
      with:
<<<<<<< HEAD
<<<<<<< HEAD
        space: promotions-manager
        fileslist: ${{ steps.files.outputs.all }}
=======
        space: PreSaleJenkinsSolution
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        fileslist: ${{ steps.files.outputs.added_modified  }}
>>>>>>> Update master_ci.yml
=======
#         fileslist: ${{ steps.files.outputs.added_modified  }}
>>>>>>> Update master_ci.yml
=======
        fileslist: ${{ steps.files.outputs.added_modified  }}
>>>>>>> Update master_ci.yml
=======
=======
        space: promotions-manager
>>>>>>> Update master_ci.yml
        files_list: ${{ steps.files.outputs.added_modified  }}
>>>>>>> Update master_ci.yml
        colony_token: ${{ secrets.COLONY_TOKEN }}
