name: Test Colony Sandbox
on:
  push:
    branches:
      - master
    pull_request:
      branches:
      - master

jobs:
  TestInsideSandbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Colony Start Sandbox
      id: start-sb
      uses: QualiSystemsLab/colony-start-sb-action@dev
      with:
        space: PreSaleJenkinsSolution
        blueprint_name: Jenkins
        inputs: 'CS_COLONY_TOKEN=ABC,SPACE_NAME=trial,IAM_ROLE=s3access-profile,BUCKET_NAME=tyest1,AWS_INSTANCE_TYPE=m5.large,JENKINS_ADMIN_PASS=admin'
        colony_token: ${{ secrets.COLONY_TOKEN }}
        timeout: 14
        branch: dev
        colony_account: colony-demo
        
    - name: Testing
      run: |
        echo "Running tests against sandbox with id: ${{ steps.start-sb.outputs.sandbox_id }}"
        #echo "${{ steps.start-sb.outputs.sandbox_shortcuts }}"
        #echo "${{ steps.start-sb.outputs.sandbox_details }}"
        #echo "${{ steps.start-sb.outputs.sandbox_id }}"

        readarray -t shortcuts <<< "$(jq '. | .[]' <<< '${{ steps.start-sb.outputs.sandbox_shortcuts }}')"
        for shortcut in ${shortcuts[@]}; do
            echo "Do something with this ${shortcut}."
        done        
      
    - name: Stop Sandbox
      uses: QualiSystemsLab/colony-end-sb-action@v0.0.1
      with:
        space: PreSaleJenkinsSolution
        colony_token: ${{ secrets.COLONY_TOKEN }}
        sandbox_id: ${{ steps.start-sb.outputs.sandbox_id }}
