name: Test Colony Sandbox
on:
  push:
    branches:
      - master
    pull_request:
      branches:
      - master

jobs:
  TestInsideSandbox:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Colony start
      id: start-sb
      uses: ddovbii/colony-start-sb-action@dev
      with:
        space: PreSaleJenkinsSolution
        blueprint_name: Jenkins
        inputs: 'CS_COLONY_TOKEN=ABC,SPACE_NAME=trial,IAM_ROLE=s3access-profile,BUCKET_NAME=tyest1,AWS_INSTANCE_TYPE=m5.large,JENKINS_ADMIN_PASS=admin'
        colony_token: ${{ secrets.COLONY_TOKEN }}
        timeout: 12
        branch: dev
        colony_account: colony-demo
        
    - name: Testing
      run: sleep 30
      
#     - name: Stop Sandbox
#       uses: QualiSystemsLab/colony-end-sb-action@dev
#       with:
#         space: PreSaleJenkinsSolution
#         colony_token: ${{ secrets.COLONY_TOKEN }}
#         sandbox_id: ${{ steps.start-sb.outputs.sandbox_id }}
